### PR TITLE
Update training printouts, code quality

### PR DESCRIPTION
**Pull request by roszcz**
I removed `tqdm` (I don't like it anymore :)), and applied the code hooks. The way of printing metrics in the terminal is very ad-hoc, but I hope it'll be easier to follow progress.

I ran a larger sweep trying to get some insight into the lambda loss settings https://wandb.ai/roszcz/midi-vq/sweeps/ima1sy6b

Main takeaway is that the pitch reconstruction was never very good, tending to repeat the same pitch multiple times:

image

I have a couple of architecture questions possibly related to this:

1. There's no positional embeddings used at any point - does it make sense to try adding it?
2. The pitch decoder is a 3-layer MLP, did you consider using an attention/transformer based decoder?

### CODE REVIEW

**Comment by roszcz** [comment]
@JasiekKaczmarczyk I left some questions in the PR, let me know what you think!

**Comment by JasiekKaczmarczyk** [comment]
Testing positional embeddings:

Purple run is without positional embeddings and pink with them. I run training for 10 epochs.
obraz
obraz

Without PE:
https://wandb.ai/jasiekkaczmarczyk/midi-vqvae/runs/0gr12sy6?workspace=user-jasiekkaczmarczyk
With PE:
https://wandb.ai/jasiekkaczmarczyk/midi-vqvae/runs/e5gcct5n?workspace=user-jasiekkaczmarczyk

The goal weighted sum is pretty similar but participation of components of this metrics (pitch acc, velocity r2, dstart r2 and duration r2) is much different.

**Comment by JasiekKaczmarczyk** [comment]
With transformer-based decoder:
obraz
obraz

https://wandb.ai/jasiekkaczmarczyk/midi-vqvae/runs/j1aphjj7?workspace=user-jasiekkaczmarczyk

**Comment by roszcz** [comment]
@JasiekKaczmarczyk Please push the code you're using to manage those runs. Ideally, we should close this PR and open a fresh one where you could document your progress

**Comment by JasiekKaczmarczyk** [comment]
Ok, I pushed the newest code.

I have some suggestions what can we test next to hopefully improve the model:
1. I think the problem may lie in 1d Conv layers, so I think switching to fully attention based network (including Downsample and Upsample blocks) will probably give better results. 
Some papers I found: 
Upsampling with attention: https://arxiv.org/pdf/2012.09904.pdf
Relative encodings: https://arxiv.org/pdf/1803.02155.pdf
Strided attention: https://paperswithcode.com/method/strided-attention
2. Maybe we could use some positional encodings for dstart and duration and use them instead of their features obtained from MLP layers. The problem is those encodings will need to be continuous.
Papers:
https://openreview.net/pdf?id=n-FqqWXnWW
3. We could try your suggestion to treat each feature as separate dimension at apply 3d Conv blocks on it (dstart and duration could be combined into single dim)

**Pull request merged**
